name: MelonKitPvP
version: '${project.version}'
main: wtf.melonthedev.melonkitpvp.Main
api-version: 1.19
authors: [ Melonthedev ]
description: A Simple KitPvP Plugin
website: melonthedev.wtf
commands:
  kitpvp:
    description: KitPvP Command
